name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint-typecheck-intent:
    name: Validate Sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Verify intent
        run: npm run verify:intent

  windows-build-gif:
    name: Build and Generate GIF (Windows)
    runs-on: windows-latest
    needs: lint-typecheck-intent
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run synthetic GIF test
        run: npm run test:gif
      - name: Upload GIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: animation-gif
          path: public/animation.gif